# Change prefix from Ctrl-b to Ctrl-a
set -g prefix C-a

# aliases
bind-key r command-prompt -p "window name:" "new-window -c '#{pane_current_path}' -n '%%'" 

# Split panes using prefix + arrow keys
bind h split-window -h -b -c "#{pane_current_path}"
bind l split-window -h -c "#{pane_current_path}"
bind k split-window -v -b -c "#{pane_current_path}"
bind j split-window -v -c "#{pane_current_path}"

# ==========
# Ghostty integration
# ==========

# This teaches tmux to recognize these CSI sequences as named keys.
set-option -g user-keys[1] "\e[100;1L"  # Cmd+h
set-option -g user-keys[2] "\e[100;1R"  # Cmd+l
set-option -g user-keys[3] "\e[100;1U"  # Cmd+k
set-option -g user-keys[4] "\e[100;1D"  # Cmd+j
set-option -g user-keys[5] "\e[100;1w"  # Cmd+w

# BIND the newly defined user keys to actions
bind-key -n User1 select-pane -L
bind-key -n User2 select-pane -R
bind-key -n User3 select-pane -U
bind-key -n User4 select-pane -D
bind-key -n User5 kill-pane
