# -----------------------------------------------------------------------------
# General
# -----------------------------------------------------------------------------
set -g mouse on
set -g base-index 1
set -g renumber-windows on
setw -g mode-keys vi

# -----------------------------------------------------------------------------
# Cursor
# -----------------------------------------------------------------------------

# Set cursor style for different modes
set -g -a terminal-overrides ',*:Ss=\E[%p1%d q:Se=\E[2 q'

# Default cursor (bar/line) in normal mode
set -g cursor-style bar

# Block cursor in copy mode
set-hook -g pane-mode-changed 'if -F "#{pane_in_mode}" "set -g cursor-style block" "set -g cursor-style bar"'

# Force the command prompt cursor to match the Catppuccin text/rosewater color
set -g prompt-cursor-colour "#f5e0dc"

# -----------------------------------------------------------------------------
# Load configs
# -----------------------------------------------------------------------------
source-file ~/.config/tmux/display.conf
source-file ~/.config/tmux/keybinds.conf
source-file ~/.config/tmux/tpm.conf
