"$schema" = 'https://starship.rs/config-schema.json'

palette = "catppuccin_mocha"

format = """
╭─ $directory\
$git_branch\
$fill\
$bun\
$c\
$cpp\
$haskell\
$java\
$lua\
$nodejs\
$python\
$rust\
$typst\
$jobs\
$time\
$cmd_duration\
$line_break\
╰─ $character\
"""

# Left side: Directory + Git
[directory]
truncation_length = 4
style = "bold lavender"

[git_branch]
style = "bold mauve"

# Right side: Devtool versions + Time
[bun]
style = "bold rosewater"
symbol = ""
format = '[${symbol} (${version} )]($style)'

[c]
style = "bold subtext-1"
symbol = ""
format = '[$symbol ($version(-$name) )]($style)'

[cpp]
style = "bold blue"
format = '[$symbol ($version(-$name) )]($style)'
disabled = false
symbol = ''
detect_extensions = ['cpp', 'cc', 'cxx', 'c++', 'h', 'hpp', 'hh', 'hxx', 'h++', 'tcc']

[haskell]
style = "bold mauve"
symbol = "󰲒"
format = '[${symbol} (${version} )]($style)'

[java]
style = "bold red"
symbol = "󰬷"
format = '[${symbol} (${version} )]($style)'

[lua]
style = "bold blue"
symbol = "󰢱"
format = '[${symbol} (${version} )]($style)'
version_format = 'v${major}.${minor}'
lua_binary = "luajit"

[nodejs]
style = "bold green"
symbol = "󰎙"
format = '[${symbol} (${version} )]($style)'

[python]
style = "bold sapphire"
symbol = ""
format = '[${symbol} ${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[rust]
style = "bold maroon"
symbol = "󱘗"
format = '[${symbol} (${version} )]($style)'

[typst]
style = "bold sky"
format = '[${symbol}(${version} )]($style)'

[cmd_duration]
style = "bold yellow"
format = '[took $duration]($style)'

[time]
disabled = false
use_12hr = true

# Input line
[character]
success_symbol = "[[󰊠](green) ❯](peach)"
error_symbol = "[[󰊠](red) ❯](peach)"

# Catppuccin Palette
[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
